name: number_animation
description: A simple and easy to use widget to help you show numbers by animation.
version: 0.2.0
homepage: https://github.com/chvin/number_animation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
